import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client'
import './globals.css'
import { PageLayout } from '@/component/page-layout'

export const metadata: Metadata = {
  title: 'Next App with Auth0',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <UserProvider>
          <PageLayout>{children}</PageLayout>
        </UserProvider>
      </body>
    </html>
  )
}
